const mergeSort = require('./mergeSort')
const twoSum = require('./twoSum')
const inversionCount = require('./inversionCount')
const containsDuplicate = require('./containsDuplicate')
const productOfArrays = require('./productOfArrays')
const maximumSubArray = require('./maximumSubArray')
const bestSum = require('./bestSum')
// const countConstruct = require('./countConstruct')
const allConstruct = require('./allConstruct')


// mergeSort.init()
// twoSum.init()
// inversionCount.init()
// containsDuplicate.init()
// productOfArrays.init()
// maximumSubArray.init()
// bestSum.init()
// countConstruct.init()
allConstruct.init()